//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__skip_one_fast_entry__(SB), NOSPLIT, $144
	NO_LOCAL_POINTERS
	WORD $0x100000a0 // adr x0, .+20
	MOVD R0, ret(FP)
	RET
	  // .p2align 4, 0x00
DATA LCDATA1<>+0x000(SB)/8, $0x8040201008040201
DATA LCDATA1<>+0x008(SB)/8, $0x8040201008040201
DATA LCDATA1<>+0x010(SB)/8, $0x0b030a0209010800
DATA LCDATA1<>+0x018(SB)/8, $0x0f070e060d050c04
DATA LCDATA1<>+0x020(SB)/8, $0x1111111111111111
DATA LCDATA1<>+0x028(SB)/8, $0x2222222222222222
DATA LCDATA1<>+0x030(SB)/8, $0x2222222222222222
DATA LCDATA1<>+0x038(SB)/8, $0x8888888888888888
DATA LCDATA1<>+0x040(SB)/8, $0x2222222222222222
DATA LCDATA1<>+0x048(SB)/8, $0x1111111111111111
DATA LCDATA1<>+0x050(SB)/8, $0x1111111111111111
DATA LCDATA1<>+0x058(SB)/8, $0x0888888888888888
DATA LCDATA1<>+0x060(SB)/8, $0x0888888888888888
DATA LCDATA1<>+0x068(SB)/8, $0x0444444444444444
DATA LCDATA1<>+0x070(SB)/8, $0x0888888888888888
DATA LCDATA1<>+0x078(SB)/8, $0x1111111111111111
DATA LCDATA1<>+0x080(SB)/8, $0x0444444444444444
DATA LCDATA1<>+0x088(SB)/8, $0x0222222222222222
DATA LCDATA1<>+0x090(SB)/8, $0x4444444444444444
DATA LCDATA1<>+0x098(SB)/8, $0x8888888888888888
GLOBL LCDATA1<>(SB), 8, $160

LCPI0_0:
    WORD $0x08040201
    WORD $0x80402010
    WORD $0x08040201
    WORD $0x80402010
LCPI0_1:
    WORD $0x09010800
    WORD $0x0b030a02
    WORD $0x0d050c04
    WORD $0x0f070e06
LCPI0_2:
    WORD $0x11111111; WORD $0x11111111
    WORD $0x22222222; WORD $0x22222222
LCPI0_3:
    WORD $0x22222222; WORD $0x22222222
    WORD $0x88888888; WORD $0x88888888
LCPI0_4:
    WORD $0x22222222; WORD $0x22222222
    WORD $0x11111111; WORD $0x11111111
LCPI0_5:
    WORD $0x11111111; WORD $0x11111111
    WORD $0x88888888; WORD $0x08888888
LCPI0_6:
    WORD $0x88888888; WORD $0x08888888
    WORD $0x44444444; WORD $0x04444444
LCPI0_7:
    WORD $0x88888888; WORD $0x08888888
    WORD $0x11111111; WORD $0x11111111
LCPI0_8:
    WORD $0x44444444; WORD $0x04444444
    WORD $0x22222222; WORD $0x02222222
LCPI0_9:
    WORD $0x44444444; WORD $0x44444444
    WORD $0x88888888; WORD $0x88888888
skip_one_fast:
    WORD $0xd101c3ff // sub    sp, sp, #112
    WORD $0xa905fbfd // stp    fp, lr, [sp, #88]
    WORD $0x910163e9 // add x9, sp, #88
    WORD $0x043f57ff // addvl    sp, sp, #-1
    WORD $0xd10043ff // sub sp, sp, #16
    WORD $0xa93ffbfd // stp    fp, lr, [sp, #-8]
    WORD $0xd10023fd // sub    fp, sp, #8
    WORD $0xa9402c0a // ldp    x10, x11, [x0]
    WORD $0xf940002c // ldr    x12, [x1]
    WORD $0xeb0b019f // cmp    x12, x11
    BHS LBB0_4
    WORD $0x386c6948 // ldrb    w8, [x10, x12]
    WORD $0x7100351f // cmp    w8, #13
    BEQ LBB0_4
    WORD $0x7100811f // cmp    w8, #32
    BEQ LBB0_4
    WORD $0x51002d08 // sub    w8, w8, #11
    WORD $0x3100091f // cmn    w8, #2
    WORD $0xaa0c03e8 // mov    x8, x12
    BLO LBB0_23
LBB0_4:
    WORD $0x91000588 // add    x8, x12, #1
    WORD $0xeb0b011f // cmp    x8, x11
    BHS LBB0_8
    WORD $0x3868694d // ldrb    w13, [x10, x8]
    WORD $0x710035bf // cmp    w13, #13
    BEQ LBB0_8
    WORD $0x710081bf // cmp    w13, #32
    BEQ LBB0_8
    WORD $0x51002dad // sub    w13, w13, #11
    WORD $0x310009bf // cmn    w13, #2
    BLO LBB0_23
LBB0_8:
    WORD $0x91000988 // add    x8, x12, #2
    WORD $0xeb0b011f // cmp    x8, x11
    BHS LBB0_12
    WORD $0x3868694d // ldrb    w13, [x10, x8]
    WORD $0x710035bf // cmp    w13, #13
    BEQ LBB0_12
    WORD $0x710081bf // cmp    w13, #32
    BEQ LBB0_12
    WORD $0x51002dad // sub    w13, w13, #11
    WORD $0x310009bf // cmn    w13, #2
    BLO LBB0_23
LBB0_12:
    WORD $0x91000d88 // add    x8, x12, #3
    WORD $0xeb0b011f // cmp    x8, x11
    BHS LBB0_16
    WORD $0x3868694d // ldrb    w13, [x10, x8]
    WORD $0x710035bf // cmp    w13, #13
    BEQ LBB0_16
    WORD $0x710081bf // cmp    w13, #32
    BEQ LBB0_16
    WORD $0x51002dad // sub    w13, w13, #11
    WORD $0x310009bf // cmn    w13, #2
    BLO LBB0_23
LBB0_16:
    WORD $0x91001188 // add    x8, x12, #4
    WORD $0xeb0b011f // cmp    x8, x11
    BHS LBB0_131
    WORD $0xd284c00d // mov    x13, #9728
    WORD $0x5280002c // mov    w12, #1
    WORD $0xf2c0002d // movk    x13, #1, lsl #32
LBB0_18:
    WORD $0x3868694e // ldrb    w14, [x10, x8]
    WORD $0x9ace218f // lsl    x15, x12, x14
    WORD $0x710081df // cmp    w14, #32
    WORD $0x8a0d01ee // and    x14, x15, x13
    WORD $0xfa4099c4 // ccmp    x14, #0, #4, ls
    BEQ LBB0_22
    WORD $0x91000508 // add    x8, x8, #1
    WORD $0xeb08017f // cmp    x11, x8
    BNE LBB0_18
    WORD $0x92800000 // mov    x0, #-1
LBB0_21:
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_22:
    WORD $0xeb0b011f // cmp    x8, x11
    BHS LBB0_85
LBB0_23:
    WORD $0x91000511 // add    x17, x8, #1
    WORD $0xf9000031 // str    x17, [x1]
    WORD $0x3868694b // ldrb    w11, [x10, x8]
    WORD $0x7101697f // cmp    w11, #90
    BGT LBB0_49
    WORD $0x7100bd7f // cmp    w11, #47
    BLE LBB0_54
    WORD $0x5100c16b // sub    w11, w11, #48
    WORD $0x7100297f // cmp    w11, #10
    BHS LBB0_121
LBB0_26:
    WORD $0xf940040b // ldr    x11, [x0, #8]
    WORD $0xcb11016c // sub    x12, x11, x17
    WORD $0x8b11014b // add    x11, x10, x17
    WORD $0xf100819f // cmp    x12, #32
    BLO LBB0_30
    WORD $0x2518e3e0 // ptrue    p0.b
    WORD $0x2538cfa0 // mov    z0.b, #125
    WORD $0x2538cba1 // mov    z1.b, #93
    WORD $0x2538c582 // mov    z2.b, #44
    WORD $0xaa1f03ed // mov    x13, xzr
LBB0_28:
    WORD $0xa400a163 // ld1b    { z3.b }, p0/z, [x11]
    WORD $0xd100212e // sub x14, x9, #8
    WORD $0x046957cf // addpl x15, x9, #-2
    WORD $0x046957b0 // addpl x16, x9, #-3
    WORD $0x2400a061 // cmpeq    p1.b, p0/z, z3.b, z0.b
    WORD $0x2401a062 // cmpeq    p2.b, p0/z, z3.b, z1.b
    WORD $0x2402a063 // cmpeq    p3.b, p0/z, z3.b, z2.b
    WORD $0xe5bf1dc1 // str    p1, [x14, #-1, mul vl]
    WORD $0xe5bf19c2 // str    p2, [x14, #-2, mul vl]
    WORD $0xe5bf15c3 // str    p3, [x14, #-3, mul vl]
    WORD $0x046957ee // addpl x14, x9, #-1
    WORD $0xb85f81ef // ldur    w15, [x15, #-8]
    WORD $0xb85f81ce // ldur    w14, [x14, #-8]
    WORD $0xb85f8210 // ldur    w16, [x16, #-8]
    WORD $0x2a0e01ee // orr    w14, w15, w14
    WORD $0x2a1001ce // orr    w14, w14, w16
    CMP $0, R14
    BNE LBB0_44
    WORD $0xd100818c // sub    x12, x12, #32
    WORD $0x9100816b // add    x11, x11, #32
    WORD $0x910081ad // add    x13, x13, #32
    WORD $0xf1007d9f // cmp    x12, #31
    BHI LBB0_28
LBB0_30:
    WORD $0xf100419f // cmp    x12, #16
    BLO LBB0_35
    WORD $0x4f01e580 // movi    v0.16b, #44
    WORD $0x4f06e7e1 // movi    v1.16b, #223
    ADR LCPI0_0, R13
    WORD $0x4f02e7a2 // movi    v2.16b, #93
    ADR LCPI0_1, R14
    WORD $0x3dc001a3 // ldr    q3, [x13, :lo12:.LCPI0_0]
    WORD $0x3dc001c4 // ldr    q4, [x14, :lo12:.LCPI0_1]
    WORD $0xaa1f03ed // mov    x13, xzr
LBB0_32:
    WORD $0x3ced6965 // ldr    q5, [x11, x13]
    WORD $0x4e211ca6 // and    v6.16b, v5.16b, v1.16b
    WORD $0x6e208ca5 // cmeq    v5.16b, v5.16b, v0.16b
    WORD $0x6e228cc6 // cmeq    v6.16b, v6.16b, v2.16b
    WORD $0x4ea51cc5 // orr    v5.16b, v6.16b, v5.16b
    WORD $0x4e231ca5 // and    v5.16b, v5.16b, v3.16b
    WORD $0x4e0400a5 // tbl    v5.16b, { v5.16b }, v4.16b
    WORD $0x4e71b8a5 // addv    h5, v5.8h
    WORD $0x1e2600ae // fmov    w14, s5
    CMP $0, R14
    BNE LBB0_124
    WORD $0xd100418c // sub    x12, x12, #16
    WORD $0x910041ad // add    x13, x13, #16
    WORD $0xf1003d9f // cmp    x12, #15
    BHI LBB0_32
    WORD $0x8b0d016b // add    x11, x11, x13
LBB0_35:
    CMP $0, R12
    BEQ LBB0_43
    WORD $0xd284c010 // mov    x16, #9728
    WORD $0x8b0c016d // add    x13, x11, x12
    WORD $0xcb0a016e // sub    x14, x11, x10
    WORD $0x5280002f // mov    w15, #1
    WORD $0xf2c20030 // movk    x16, #4097, lsl #32
LBB0_37:
    WORD $0x39400171 // ldrb    w17, [x11]
    WORD $0x7100b23f // cmp    w17, #44
    BHI LBB0_39
    WORD $0x9ad121f2 // lsl    x18, x15, x17
    WORD $0xea10025f // tst    x18, x16
    BNE LBB0_129
LBB0_39:
    WORD $0x7101f63f // cmp    w17, #125
    BEQ LBB0_129
    WORD $0x7101763f // cmp    w17, #93
    BEQ LBB0_129
    WORD $0xf100058c // subs    x12, x12, #1
    WORD $0x9100056b // add    x11, x11, #1
    WORD $0x910005ce // add    x14, x14, #1
    BNE LBB0_37
    WORD $0xaa0d03eb // mov    x11, x13
LBB0_43:
    WORD $0xcb0a016a // sub    x10, x11, x10
    WORD $0xf900002a // str    x10, [x1]
    WORD $0xaa0803e0 // mov    x0, x8
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_44:
    WORD $0x5ac001cc // rbit    w12, w14
    WORD $0xcb0a016e // sub    x14, x11, x10
    WORD $0x5ac0118b // clz    w11, w12
    WORD $0x8b0b01cc // add    x12, x14, x11
    WORD $0xf100059f // cmp    x12, #1
    WORD $0xf900002c // str    x12, [x1]
    BLT LBB0_48
    WORD $0x8b0d016b // add    x11, x11, x13
    WORD $0xd284c00d // mov    x13, #9728
    WORD $0x8b08014a // add    x10, x10, x8
    WORD $0x5280002c // mov    w12, #1
    WORD $0xf2c0002d // movk    x13, #1, lsl #32
LBB0_46:
    WORD $0x386b694e // ldrb    w14, [x10, x11]
    WORD $0x9ace218f // lsl    x15, x12, x14
    WORD $0x710081df // cmp    w14, #32
    WORD $0x8a0d01ee // and    x14, x15, x13
    WORD $0xfa4099c4 // ccmp    x14, #0, #4, ls
    BEQ LBB0_48
    WORD $0x8b0b010e // add    x14, x8, x11
    WORD $0xd100056b // sub    x11, x11, #1
    WORD $0x8b0b010f // add    x15, x8, x11
    WORD $0xf900002e // str    x14, [x1]
    WORD $0x910009ef // add    x15, x15, #2
    WORD $0xf10005ff // cmp    x15, #1
    BGT LBB0_46
LBB0_48:
    WORD $0xaa0803e0 // mov    x0, x8
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_49:
    WORD $0x7101b57f // cmp    w11, #109
    BLE LBB0_57
    WORD $0x7101b97f // cmp    w11, #110
    BEQ LBB0_84
    WORD $0x7101d17f // cmp    w11, #116
    BEQ LBB0_84
    WORD $0x7101ed7f // cmp    w11, #123
    BNE LBB0_121
    ADR LCPI0_2, R16
    WORD $0x2518e3e0 // ptrue    p0.b
    ADR LCPI0_4, R18_PLATFORM
    WORD $0x3dc00202 // ldr    q2, [x16, :lo12:.LCPI0_2]
    ADR LCPI0_3, R16
    WORD $0x25d8e041 // ptrue    p1.d, vl2
    WORD $0x3dc00203 // ldr    q3, [x16, :lo12:.LCPI0_3]
    ADR LCPI0_5, R16
    WORD $0x3dc00244 // ldr    q4, [x18, :lo12:.LCPI0_4]
    WORD $0x4f02e485 // movi    v5.16b, #68
    ADR LCPI0_6, R18_PLATFORM
    WORD $0x3dc00206 // ldr    q6, [x16, :lo12:.LCPI0_5]
    ADR LCPI0_7, R16
    WORD $0x6f00e411 // movi    v17.2d, #0000000000000000
    WORD $0xf940040e // ldr    x14, [x0, #8]
    WORD $0x2538c440 // mov    z0.b, #34
    WORD $0x2538cb81 // mov    z1.b, #92
    WORD $0x3dc00247 // ldr    q7, [x18, :lo12:.LCPI0_6]
    WORD $0x3dc00210 // ldr    q16, [x16, :lo12:.LCPI0_7]
    ADR LCPI0_8, R16
    ADR LCPI0_9, R18_PLATFORM
    WORD $0x2538cf72 // mov    z18.b, #123
    WORD $0x2538cfb3 // mov    z19.b, #125
    WORD $0x3dc00214 // ldr    q20, [x16, :lo12:.LCPI0_8]
    WORD $0x910043f0 // add    x16, sp, #16
    WORD $0x3dc00255 // ldr    q21, [x18, :lo12:.LCPI0_9]
    WORD $0xaa1f03ef // mov    x15, xzr
    WORD $0xaa1f03ed // mov    x13, xzr
    WORD $0xaa1f03eb // mov    x11, xzr
    WORD $0xaa1f03ec // mov    x12, xzr
    WORD $0xcb1101ce // sub    x14, x14, x17
    WORD $0x8b110142 // add    x2, x10, x17
    WORD $0x9100820a // add    x10, x16, #32
    WORD $0x52800411 // mov    w17, #32
    B LBB0_61
LBB0_54:
    CMP $0, R11
    BEQ LBB0_85
    WORD $0x7100897f // cmp    w11, #34
    BEQ LBB0_86
    WORD $0x7100b57f // cmp    w11, #45
    BEQ LBB0_26
    B LBB0_121
LBB0_57:
    WORD $0x71016d7f // cmp    w11, #91
    BEQ LBB0_95
    WORD $0x7101997f // cmp    w11, #102
    BNE LBB0_121
    WORD $0xf940040b // ldr    x11, [x0, #8]
    WORD $0x9100150a // add    x10, x8, #5
    WORD $0xeb0b015f // cmp    x10, x11
    BHI LBB0_85
    B LBB0_123
LBB0_60:
    WORD $0x9e670056 // fmov    d22, x2
    WORD $0x937ffdef // asr    x15, x15, #63
    WORD $0x91008062 // add    x2, x3, #32
    WORD $0x0e205ad6 // cnt    v22.8b, v22.8b
    WORD $0x2e303ad6 // uaddlv    h22, v22.8b
    WORD $0x1e2602ce // fmov    w14, s22
    WORD $0x8b0b01cb // add    x11, x14, x11
    WORD $0xaa1203ee // mov    x14, x18
LBB0_61:
    WORD $0xf10101d2 // subs    x18, x14, #64
    BLT LBB0_68
LBB0_62:
    WORD $0xa400a056 // ld1b    { z22.b }, p0/z, [x2]
    WORD $0xa4114057 // ld1b    { z23.b }, p0/z, [x2, x17]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x2400a2c2 // cmpeq    p2.b, p0/z, z22.b, z0.b
    WORD $0x2400a2e3 // cmpeq    p3.b, p0/z, z23.b, z0.b
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0xa400a056 // ld1b    { z22.b }, p0/z, [x2]
    WORD $0xa4114057 // ld1b    { z23.b }, p0/z, [x2, x17]
    WORD $0xb85f83c3 // ldur    w3, [lr, #-8]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x2401a2c2 // cmpeq    p2.b, p0/z, z22.b, z1.b
    WORD $0x2401a2e3 // cmpeq    p3.b, p0/z, z23.b, z1.b
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c4 // ldur    w4, [lr, #-8]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c5 // ldur    w5, [lr, #-8]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0xb85f83c6 // ldur    w6, [lr, #-8]
    WORD $0xaa0580c5 // orr    x5, x6, x5, lsl #32
    WORD $0xaa0d00a6 // orr    x6, x5, x13
    CMP $0, R6
    BNE LBB0_64
    WORD $0xaa1f03ed // mov    x13, xzr
    WORD $0xaa1f03e5 // mov    x5, xzr
    B LBB0_65
LBB0_64:
    WORD $0x8a2d00a6 // bic    x6, x5, x13
    WORD $0xaa0605a7 // orr    x7, x13, x6, lsl #1
    WORD $0x8a2700ad // bic    x13, x5, x7
    WORD $0x9201f1ad // and    x13, x13, #0xaaaaaaaaaaaaaaaa
    WORD $0xab0601ad // adds    x13, x13, x6
    WORD $0xd37ff9ad // lsl    x13, x13, #1
    WORD $0xd200f1a5 // eor    x5, x13, #0x5555555555555555
    WORD $0x1a9f37ed // cset    w13, hs
    WORD $0x8a0700a5 // and    x5, x5, x7
LBB0_65:
    WORD $0xaa048063 // orr    x3, x3, x4, lsl #32
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x8a250063 // bic    x3, x3, x5
    WORD $0x4e080c76 // dup    v22.2d, x3
    WORD $0x9202e064 // and    x4, x3, #0x4444444444444444
    WORD $0x9201e063 // and    x3, x3, #0x8888888888888888
    WORD $0x4e080c97 // dup    v23.2d, x4
    WORD $0x4e080c7a // dup    v26.2d, x3
    WORD $0x0420befb // movprfx    z27, z23
    WORD $0x04d0045b // mul    z27.d, p1/m, z27.d, z2.d
    WORD $0x0420bf5d // movprfx    z29, z26
    WORD $0x04d0061d // mul    z29.d, p1/m, z29.d, z16.d
    WORD $0x91008043 // add    x3, x2, #32
    WORD $0x4e221ed6 // and    v22.16b, v22.16b, v2.16b
    WORD $0x0420bedc // movprfx    z28, z22
    WORD $0x04d004bc // mul    z28.d, p1/m, z28.d, z5.d
    WORD $0x6e3b1f9b // eor    v27.16b, v28.16b, v27.16b
    WORD $0x04d004f7 // mul    z23.d, p1/m, z23.d, z7.d
    WORD $0x04d0069a // mul    z26.d, p1/m, z26.d, z20.d
    WORD $0x4e0806d8 // dup    v24.2d, v22.d[0]
    WORD $0x4e1806d9 // dup    v25.2d, v22.d[1]
    WORD $0x6e1642d6 // ext    v22.16b, v22.16b, v22.16b, #8
    WORD $0x6e3a1ef7 // eor    v23.16b, v23.16b, v26.16b
    WORD $0xa400a05a // ld1b    { z26.b }, p0/z, [x2]
    WORD $0x04d00498 // mul    z24.d, p1/m, z24.d, z4.d
    WORD $0x04d004d9 // mul    z25.d, p1/m, z25.d, z6.d
    WORD $0x04d00476 // mul    z22.d, p1/m, z22.d, z3.d
    WORD $0x2412a342 // cmpeq    p2.b, p0/z, z26.b, z18.b
    WORD $0x6e391f18 // eor    v24.16b, v24.16b, v25.16b
    WORD $0x6e3d1f79 // eor    v25.16b, v27.16b, v29.16b
    WORD $0xa400a07b // ld1b    { z27.b }, p0/z, [x3]
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0x6e371f17 // eor    v23.16b, v24.16b, v23.16b
    WORD $0x6e391ed6 // eor    v22.16b, v22.16b, v25.16b
    WORD $0x2412a363 // cmpeq    p3.b, p0/z, z27.b, z18.b
    WORD $0x4e351ed6 // and    v22.16b, v22.16b, v21.16b
    WORD $0x4e241ef7 // and    v23.16b, v23.16b, v4.16b
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0xa400a078 // ld1b    { z24.b }, p0/z, [x3]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0x4eb61ef6 // orr    v22.16b, v23.16b, v22.16b
    WORD $0xa400a057 // ld1b    { z23.b }, p0/z, [x2]
    WORD $0xb85f83c2 // ldur    w2, [lr, #-8]
    WORD $0x2413a303 // cmpeq    p3.b, p0/z, z24.b, z19.b
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x2413a2e2 // cmpeq    p2.b, p0/z, z23.b, z19.b
    WORD $0x6e1642d9 // ext    v25.16b, v22.16b, v22.16b, #8
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c4 // ldur    w4, [lr, #-8]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x0eb91ed6 // orr    v22.8b, v22.8b, v25.8b
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c5 // ldur    w5, [lr, #-8]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0xaa048042 // orr    x2, x2, x4, lsl #32
    WORD $0xb85f83c6 // ldur    w6, [lr, #-8]
    WORD $0xaa0580c5 // orr    x5, x6, x5, lsl #32
    WORD $0x9e6602c6 // fmov    x6, d22
    WORD $0xca0f00cf // eor    x15, x6, x15
    WORD $0xea2f00a4 // bics    x4, x5, x15
    WORD $0x8a2f0042 // bic    x2, x2, x15
    BEQ LBB0_60
LBB0_66:
    WORD $0xd1000485 // sub    x5, x4, #1
    WORD $0x8a0200a6 // and    x6, x5, x2
    WORD $0x9e6700d6 // fmov    d22, x6
    WORD $0x0e205ad6 // cnt    v22.8b, v22.8b
    WORD $0x2e303ad6 // uaddlv    h22, v22.8b
    WORD $0x1e2602c6 // fmov    w6, s22
    WORD $0x8b0b00c6 // add    x6, x6, x11
    WORD $0xeb0c00df // cmp    x6, x12
    BLS LBB0_120
    WORD $0xea0400a4 // ands    x4, x5, x4
    WORD $0x9100058c // add    x12, x12, #1
    BNE LBB0_66
    B LBB0_60
LBB0_68:
    WORD $0xf10001df // cmp    x14, #0
    BLE LBB0_130
    WORD $0x92402c43 // and    x3, x2, #0xfff
    WORD $0xad00c7f1 // stp    q17, q17, [sp, #16]
    WORD $0xf13f047f // cmp    x3, #4033
    WORD $0xad01c7f1 // stp    q17, q17, [sp, #48]
    BLO LBB0_62
    WORD $0xf10081c4 // subs    x4, x14, #32
    BLO LBB0_72
    WORD $0xa400a056 // ld1b    { z22.b }, p0/z, [x2]
    WORD $0x91008042 // add    x2, x2, #32
    WORD $0xaa0a03e3 // mov    x3, x10
    WORD $0xe400e216 // st1b    { z22.b }, p0, [x16]
    B LBB0_73
LBB0_72:
    WORD $0x910043e3 // add    x3, sp, #16
    WORD $0xaa0e03e4 // mov    x4, x14
LBB0_73:
    WORD $0xf1004085 // subs    x5, x4, #16
    BLO LBB0_79
    WORD $0x3cc10456 // ldr    q22, [x2], #16
    WORD $0xaa0503e4 // mov    x4, x5
    WORD $0x3c810476 // str    q22, [x3], #16
    WORD $0xf10020a5 // subs    x5, x5, #8
    BHS LBB0_80
LBB0_75:
    WORD $0xf1001085 // subs    x5, x4, #4
    BLO LBB0_81
LBB0_76:
    WORD $0xb8404444 // ldr    w4, [x2], #4
    WORD $0xb8004464 // str    w4, [x3], #4
    WORD $0xaa0503e4 // mov    x4, x5
    WORD $0xf10008a5 // subs    x5, x5, #2
    BHS LBB0_82
LBB0_77:
    CMP $0, R4
    BEQ LBB0_83
LBB0_78:
    WORD $0x39400044 // ldrb    w4, [x2]
    WORD $0x910043e2 // add    x2, sp, #16
    WORD $0x39000064 // strb    w4, [x3]
    B LBB0_62
LBB0_79:
    WORD $0xf1002085 // subs    x5, x4, #8
    BLO LBB0_75
LBB0_80:
    WORD $0xf8408444 // ldr    x4, [x2], #8
    WORD $0xf8008464 // str    x4, [x3], #8
    WORD $0xaa0503e4 // mov    x4, x5
    WORD $0xf10010a5 // subs    x5, x5, #4
    BHS LBB0_76
LBB0_81:
    WORD $0xf1000885 // subs    x5, x4, #2
    BLO LBB0_77
LBB0_82:
    WORD $0x78402444 // ldrh    w4, [x2], #2
    WORD $0x78002464 // strh    w4, [x3], #2
    WORD $0xaa0503e4 // mov    x4, x5
    CMP $0, R5
    BNE LBB0_78
LBB0_83:
    WORD $0x910043e2 // add    x2, sp, #16
    B LBB0_62
LBB0_84:
    WORD $0xf940040b // ldr    x11, [x0, #8]
    WORD $0x9100110a // add    x10, x8, #4
    WORD $0xeb0b015f // cmp    x10, x11
    BLS LBB0_123
LBB0_85:
    WORD $0x92800000 // mov    x0, #-1
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_86:
    WORD $0xf940040c // ldr    x12, [x0, #8]
    WORD $0xcb11018b // sub    x11, x12, x17
    WORD $0xf100817f // cmp    x11, #32
    BLT LBB0_128
    WORD $0x2518e3e0 // ptrue    p0.b
    WORD $0x2538c440 // mov    z0.b, #34
    WORD $0x2538cb81 // mov    z1.b, #92
    WORD $0xaa1f03eb // mov    x11, xzr
    WORD $0xaa1f03ee // mov    x14, xzr
    WORD $0x8b08014d // add    x13, x10, x8
    WORD $0xcb08018c // sub    x12, x12, x8
    WORD $0x528003ef // mov    w15, #31
    WORD $0x52800030 // mov    w16, #1
LBB0_88:
    WORD $0x8b0b01b1 // add    x17, x13, x11
    WORD $0xd1002132 // sub x18, x9, #8
    WORD $0xa4104222 // ld1b    { z2.b }, p0/z, [x17, x16]
    WORD $0xd1002131 // sub x17, x9, #8
    WORD $0x2400a041 // cmpeq    p1.b, p0/z, z2.b, z0.b
    WORD $0x2401a042 // cmpeq    p2.b, p0/z, z2.b, z1.b
    WORD $0xe5bf1e21 // str    p1, [x17, #-1, mul vl]
    WORD $0x046957f1 // addpl x17, x9, #-1
    WORD $0xb85f8231 // ldur    w17, [x17, #-8]
    WORD $0xe5bf1e42 // str    p2, [x18, #-1, mul vl]
    WORD $0x046957f2 // addpl x18, x9, #-1
    WORD $0xb85f8252 // ldur    w18, [x18, #-8]
    CMP $0, R18_PLATFORM
    BNE LBB0_90
    CMP $0, R14
    BEQ LBB0_91
LBB0_90:
    WORD $0x0a2e0240 // bic    w0, w18, w14
    WORD $0x2a0005ce // orr    w14, w14, w0, lsl #1
    WORD $0x0a2e0252 // bic    w18, w18, w14
    WORD $0x1201f252 // and    w18, w18, #0xaaaaaaaa
    WORD $0x2b000252 // adds    w18, w18, w0
    WORD $0x531f7a52 // lsl    w18, w18, #1
    WORD $0x5200f252 // eor    w18, w18, #0x55555555
    WORD $0x0a0e024e // and    w14, w18, w14
    WORD $0x2a2e03f2 // mvn    w18, w14
    WORD $0x1a9f37ee // cset    w14, hs
    WORD $0x8a110251 // and    x17, x18, x17
LBB0_91:
    CMP $0, R17
    BNE LBB0_122
    WORD $0xd10081ef // sub    x15, x15, #32
    WORD $0x9100816b // add    x11, x11, #32
    WORD $0x8b0f0191 // add    x17, x12, x15
    WORD $0xf100fe3f // cmp    x17, #63
    BGT LBB0_88
    CMP $0, R14
    BNE LBB0_132
    WORD $0x8b08014d // add    x13, x10, x8
    WORD $0x8b0b01ad // add    x13, x13, x11
    WORD $0xaa2b03eb // mvn    x11, x11
    WORD $0x910005ad // add    x13, x13, #1
    WORD $0x8b0c016b // add    x11, x11, x12
    WORD $0x92800000 // mov    x0, #-1
    WORD $0xf100057f // cmp    x11, #1
    BGE LBB0_135
    B LBB0_21
LBB0_95:
    ADR LCPI0_2, R16
    WORD $0x2518e3e0 // ptrue    p0.b
    ADR LCPI0_4, R18_PLATFORM
    WORD $0x3dc00202 // ldr    q2, [x16, :lo12:.LCPI0_2]
    ADR LCPI0_3, R16
    WORD $0x25d8e041 // ptrue    p1.d, vl2
    WORD $0x3dc00203 // ldr    q3, [x16, :lo12:.LCPI0_3]
    ADR LCPI0_5, R16
    WORD $0x3dc00244 // ldr    q4, [x18, :lo12:.LCPI0_4]
    WORD $0x4f02e485 // movi    v5.16b, #68
    ADR LCPI0_6, R18_PLATFORM
    WORD $0x3dc00206 // ldr    q6, [x16, :lo12:.LCPI0_5]
    ADR LCPI0_7, R16
    WORD $0x6f00e411 // movi    v17.2d, #0000000000000000
    WORD $0xf940040e // ldr    x14, [x0, #8]
    WORD $0x2538c440 // mov    z0.b, #34
    WORD $0x2538cb81 // mov    z1.b, #92
    WORD $0x3dc00247 // ldr    q7, [x18, :lo12:.LCPI0_6]
    WORD $0x3dc00210 // ldr    q16, [x16, :lo12:.LCPI0_7]
    ADR LCPI0_8, R16
    ADR LCPI0_9, R18_PLATFORM
    WORD $0x2538cb72 // mov    z18.b, #91
    WORD $0x2538cbb3 // mov    z19.b, #93
    WORD $0x3dc00214 // ldr    q20, [x16, :lo12:.LCPI0_8]
    WORD $0x910043f0 // add    x16, sp, #16
    WORD $0x3dc00255 // ldr    q21, [x18, :lo12:.LCPI0_9]
    WORD $0xaa1f03ef // mov    x15, xzr
    WORD $0xaa1f03ed // mov    x13, xzr
    WORD $0xaa1f03eb // mov    x11, xzr
    WORD $0xaa1f03ec // mov    x12, xzr
    WORD $0xcb1101ce // sub    x14, x14, x17
    WORD $0x8b110142 // add    x2, x10, x17
    WORD $0x9100820a // add    x10, x16, #32
    WORD $0x52800411 // mov    w17, #32
    B LBB0_97
LBB0_96:
    WORD $0x9e670056 // fmov    d22, x2
    WORD $0x937ffdef // asr    x15, x15, #63
    WORD $0x91008062 // add    x2, x3, #32
    WORD $0x0e205ad6 // cnt    v22.8b, v22.8b
    WORD $0x2e303ad6 // uaddlv    h22, v22.8b
    WORD $0x1e2602ce // fmov    w14, s22
    WORD $0x8b0b01cb // add    x11, x14, x11
    WORD $0xaa1203ee // mov    x14, x18
LBB0_97:
    WORD $0xf10101d2 // subs    x18, x14, #64
    BLT LBB0_104
LBB0_98:
    WORD $0xa400a056 // ld1b    { z22.b }, p0/z, [x2]
    WORD $0xa4114057 // ld1b    { z23.b }, p0/z, [x2, x17]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x2400a2c2 // cmpeq    p2.b, p0/z, z22.b, z0.b
    WORD $0x2400a2e3 // cmpeq    p3.b, p0/z, z23.b, z0.b
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0xa400a056 // ld1b    { z22.b }, p0/z, [x2]
    WORD $0xa4114057 // ld1b    { z23.b }, p0/z, [x2, x17]
    WORD $0xb85f83c3 // ldur    w3, [lr, #-8]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x2401a2c2 // cmpeq    p2.b, p0/z, z22.b, z1.b
    WORD $0x2401a2e3 // cmpeq    p3.b, p0/z, z23.b, z1.b
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c4 // ldur    w4, [lr, #-8]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c5 // ldur    w5, [lr, #-8]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0xb85f83c6 // ldur    w6, [lr, #-8]
    WORD $0xaa0580c5 // orr    x5, x6, x5, lsl #32
    WORD $0xaa0d00a6 // orr    x6, x5, x13
    CMP $0, R6
    BNE LBB0_100
    WORD $0xaa1f03ed // mov    x13, xzr
    WORD $0xaa1f03e5 // mov    x5, xzr
    B LBB0_101
LBB0_100:
    WORD $0x8a2d00a6 // bic    x6, x5, x13
    WORD $0xaa0605a7 // orr    x7, x13, x6, lsl #1
    WORD $0x8a2700ad // bic    x13, x5, x7
    WORD $0x9201f1ad // and    x13, x13, #0xaaaaaaaaaaaaaaaa
    WORD $0xab0601ad // adds    x13, x13, x6
    WORD $0xd37ff9ad // lsl    x13, x13, #1
    WORD $0xd200f1a5 // eor    x5, x13, #0x5555555555555555
    WORD $0x1a9f37ed // cset    w13, hs
    WORD $0x8a0700a5 // and    x5, x5, x7
LBB0_101:
    WORD $0xaa048063 // orr    x3, x3, x4, lsl #32
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x8a250063 // bic    x3, x3, x5
    WORD $0x4e080c76 // dup    v22.2d, x3
    WORD $0x9202e064 // and    x4, x3, #0x4444444444444444
    WORD $0x9201e063 // and    x3, x3, #0x8888888888888888
    WORD $0x4e080c97 // dup    v23.2d, x4
    WORD $0x4e080c7a // dup    v26.2d, x3
    WORD $0x0420befb // movprfx    z27, z23
    WORD $0x04d0045b // mul    z27.d, p1/m, z27.d, z2.d
    WORD $0x0420bf5d // movprfx    z29, z26
    WORD $0x04d0061d // mul    z29.d, p1/m, z29.d, z16.d
    WORD $0x91008043 // add    x3, x2, #32
    WORD $0x4e221ed6 // and    v22.16b, v22.16b, v2.16b
    WORD $0x0420bedc // movprfx    z28, z22
    WORD $0x04d004bc // mul    z28.d, p1/m, z28.d, z5.d
    WORD $0x6e3b1f9b // eor    v27.16b, v28.16b, v27.16b
    WORD $0x04d004f7 // mul    z23.d, p1/m, z23.d, z7.d
    WORD $0x04d0069a // mul    z26.d, p1/m, z26.d, z20.d
    WORD $0x4e0806d8 // dup    v24.2d, v22.d[0]
    WORD $0x4e1806d9 // dup    v25.2d, v22.d[1]
    WORD $0x6e1642d6 // ext    v22.16b, v22.16b, v22.16b, #8
    WORD $0x6e3a1ef7 // eor    v23.16b, v23.16b, v26.16b
    WORD $0xa400a05a // ld1b    { z26.b }, p0/z, [x2]
    WORD $0x04d00498 // mul    z24.d, p1/m, z24.d, z4.d
    WORD $0x04d004d9 // mul    z25.d, p1/m, z25.d, z6.d
    WORD $0x04d00476 // mul    z22.d, p1/m, z22.d, z3.d
    WORD $0x2412a342 // cmpeq    p2.b, p0/z, z26.b, z18.b
    WORD $0x6e391f18 // eor    v24.16b, v24.16b, v25.16b
    WORD $0x6e3d1f79 // eor    v25.16b, v27.16b, v29.16b
    WORD $0xa400a07b // ld1b    { z27.b }, p0/z, [x3]
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0x6e371f17 // eor    v23.16b, v24.16b, v23.16b
    WORD $0x6e391ed6 // eor    v22.16b, v22.16b, v25.16b
    WORD $0x2412a363 // cmpeq    p3.b, p0/z, z27.b, z18.b
    WORD $0x4e351ed6 // and    v22.16b, v22.16b, v21.16b
    WORD $0x4e241ef7 // and    v23.16b, v23.16b, v4.16b
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0xa400a078 // ld1b    { z24.b }, p0/z, [x3]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0x4eb61ef6 // orr    v22.16b, v23.16b, v22.16b
    WORD $0xa400a057 // ld1b    { z23.b }, p0/z, [x2]
    WORD $0xb85f83c2 // ldur    w2, [lr, #-8]
    WORD $0x2413a303 // cmpeq    p3.b, p0/z, z24.b, z19.b
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x2413a2e2 // cmpeq    p2.b, p0/z, z23.b, z19.b
    WORD $0x6e1642d9 // ext    v25.16b, v22.16b, v22.16b, #8
    WORD $0xe5bf1fc2 // str    p2, [lr, #-1, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c4 // ldur    w4, [lr, #-8]
    WORD $0xd100213e // sub lr, x9, #8
    WORD $0x0eb91ed6 // orr    v22.8b, v22.8b, v25.8b
    WORD $0xe5bf1bc3 // str    p3, [lr, #-2, mul vl]
    WORD $0x046957de // addpl lr, x9, #-2
    WORD $0xb85f83c5 // ldur    w5, [lr, #-8]
    WORD $0x046957fe // addpl lr, x9, #-1
    WORD $0xaa048042 // orr    x2, x2, x4, lsl #32
    WORD $0xb85f83c6 // ldur    w6, [lr, #-8]
    WORD $0xaa0580c5 // orr    x5, x6, x5, lsl #32
    WORD $0x9e6602c6 // fmov    x6, d22
    WORD $0xca0f00cf // eor    x15, x6, x15
    WORD $0xea2f00a4 // bics    x4, x5, x15
    WORD $0x8a2f0042 // bic    x2, x2, x15
    BEQ LBB0_96
LBB0_102:
    WORD $0xd1000485 // sub    x5, x4, #1
    WORD $0x8a0200a6 // and    x6, x5, x2
    WORD $0x9e6700d6 // fmov    d22, x6
    WORD $0x0e205ad6 // cnt    v22.8b, v22.8b
    WORD $0x2e303ad6 // uaddlv    h22, v22.8b
    WORD $0x1e2602c6 // fmov    w6, s22
    WORD $0x8b0b00c6 // add    x6, x6, x11
    WORD $0xeb0c00df // cmp    x6, x12
    BLS LBB0_120
    WORD $0xea0400a4 // ands    x4, x5, x4
    WORD $0x9100058c // add    x12, x12, #1
    BNE LBB0_102
    B LBB0_96
LBB0_104:
    WORD $0xf10001df // cmp    x14, #0
    BLE LBB0_130
    WORD $0x92402c43 // and    x3, x2, #0xfff
    WORD $0xad00c7f1 // stp    q17, q17, [sp, #16]
    WORD $0xf13f047f // cmp    x3, #4033
    WORD $0xad01c7f1 // stp    q17, q17, [sp, #48]
    BLO LBB0_98
    WORD $0xf10081c4 // subs    x4, x14, #32
    BLO LBB0_108
    WORD $0xa400a056 // ld1b    { z22.b }, p0/z, [x2]
    WORD $0x91008042 // add    x2, x2, #32
    WORD $0xaa0a03e3 // mov    x3, x10
    WORD $0xe400e216 // st1b    { z22.b }, p0, [x16]
    B LBB0_109
LBB0_108:
    WORD $0x910043e3 // add    x3, sp, #16
    WORD $0xaa0e03e4 // mov    x4, x14
LBB0_109:
    WORD $0xf1004085 // subs    x5, x4, #16
    BLO LBB0_115
    WORD $0x3cc10456 // ldr    q22, [x2], #16
    WORD $0xaa0503e4 // mov    x4, x5
    WORD $0x3c810476 // str    q22, [x3], #16
    WORD $0xf10020a5 // subs    x5, x5, #8
    BHS LBB0_116
LBB0_111:
    WORD $0xf1001085 // subs    x5, x4, #4
    BLO LBB0_117
LBB0_112:
    WORD $0xb8404444 // ldr    w4, [x2], #4
    WORD $0xb8004464 // str    w4, [x3], #4
    WORD $0xaa0503e4 // mov    x4, x5
    WORD $0xf10008a5 // subs    x5, x5, #2
    BHS LBB0_118
LBB0_113:
    CMP $0, R4
    BEQ LBB0_119
LBB0_114:
    WORD $0x39400044 // ldrb    w4, [x2]
    WORD $0x910043e2 // add    x2, sp, #16
    WORD $0x39000064 // strb    w4, [x3]
    B LBB0_98
LBB0_115:
    WORD $0xf1002085 // subs    x5, x4, #8
    BLO LBB0_111
LBB0_116:
    WORD $0xf8408444 // ldr    x4, [x2], #8
    WORD $0xf8008464 // str    x4, [x3], #8
    WORD $0xaa0503e4 // mov    x4, x5
    WORD $0xf10010a5 // subs    x5, x5, #4
    BHS LBB0_112
LBB0_117:
    WORD $0xf1000885 // subs    x5, x4, #2
    BLO LBB0_113
LBB0_118:
    WORD $0x78402444 // ldrh    w4, [x2], #2
    WORD $0x78002464 // strh    w4, [x3], #2
    WORD $0xaa0503e4 // mov    x4, x5
    CMP $0, R5
    BNE LBB0_114
LBB0_119:
    WORD $0x910043e2 // add    x2, sp, #16
    B LBB0_98
LBB0_120:
    WORD $0xdac0008a // rbit    x10, x4
    WORD $0xf940040b // ldr    x11, [x0, #8]
    WORD $0xdac0114a // clz    x10, x10
    WORD $0xcb0e014a // sub    x10, x10, x14
    WORD $0x8b0b014a // add    x10, x10, x11
    WORD $0x9100054b // add    x11, x10, #1
    WORD $0xf900002b // str    x11, [x1]
    WORD $0xf940040c // ldr    x12, [x0, #8]
    WORD $0xeb0c017f // cmp    x11, x12
    WORD $0x9a8a258a // csinc    x10, x12, x10, hs
    WORD $0xda9f9100 // csinv    x0, x8, xzr, ls
    WORD $0xf900002a // str    x10, [x1]
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_121:
    WORD $0xf9000028 // str    x8, [x1]
    WORD $0x92800020 // mov    x0, #-2
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_122:
    WORD $0xdac0022a // rbit    x10, x17
    WORD $0x8b0b010b // add    x11, x8, x11
    WORD $0xdac0114a // clz    x10, x10
    WORD $0x8b0b014a // add    x10, x10, x11
    WORD $0x9100094a // add    x10, x10, #2
LBB0_123:
    WORD $0xf900002a // str    x10, [x1]
    WORD $0xaa0803e0 // mov    x0, x8
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_124:
    WORD $0x5ac001cc // rbit    w12, w14
    WORD $0xcb0a016a // sub    x10, x11, x10
    WORD $0x8b0d014e // add    x14, x10, x13
    WORD $0x5ac0118c // clz    w12, w12
    WORD $0x8b0e018e // add    x14, x12, x14
    WORD $0xf10005df // cmp    x14, #1
    WORD $0xf900002e // str    x14, [x1]
    BLT LBB0_48
    WORD $0xd284c00e // mov    x14, #9728
    WORD $0x8b0d018c // add    x12, x12, x13
    WORD $0xd100056b // sub    x11, x11, #1
    WORD $0x5280002d // mov    w13, #1
    WORD $0xf2c0002e // movk    x14, #1, lsl #32
LBB0_126:
    WORD $0x386c696f // ldrb    w15, [x11, x12]
    WORD $0x9acf21b0 // lsl    x16, x13, x15
    WORD $0x710081ff // cmp    w15, #32
    WORD $0x8a0e020f // and    x15, x16, x14
    WORD $0xfa4099e4 // ccmp    x15, #0, #4, ls
    BEQ LBB0_48
    WORD $0x8b0c014f // add    x15, x10, x12
    WORD $0xd100058c // sub    x12, x12, #1
    WORD $0x8b0c0150 // add    x16, x10, x12
    WORD $0xd10005ef // sub    x15, x15, #1
    WORD $0x91000610 // add    x16, x16, #1
    WORD $0xf900002f // str    x15, [x1]
    WORD $0xf100061f // cmp    x16, #1
    BGT LBB0_126
    B LBB0_48
LBB0_128:
    WORD $0x8b11014d // add    x13, x10, x17
    WORD $0x92800000 // mov    x0, #-1
    WORD $0xf100057f // cmp    x11, #1
    BGE LBB0_135
    B LBB0_21
LBB0_129:
    WORD $0xf900002e // str    x14, [x1]
    WORD $0xaa0803e0 // mov    x0, x8
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_130:
    WORD $0xf9400408 // ldr    x8, [x0, #8]
LBB0_131:
    WORD $0xf9000028 // str    x8, [x1]
    WORD $0x92800000 // mov    x0, #-1
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
LBB0_132:
    WORD $0xd100058d // sub    x13, x12, #1
    WORD $0xeb0b01bf // cmp    x13, x11
    BEQ LBB0_85
    WORD $0x8b08014d // add    x13, x10, x8
    WORD $0x8b0b01ad // add    x13, x13, x11
    WORD $0xcb0b018b // sub    x11, x12, x11
    WORD $0x910009ad // add    x13, x13, #2
    WORD $0xd100096b // sub    x11, x11, #2
    WORD $0x92800000 // mov    x0, #-1
    WORD $0xf100057f // cmp    x11, #1
    BGE LBB0_135
    B LBB0_21
LBB0_134:
    WORD $0x9280002c // mov    x12, #-2
    WORD $0x5280004e // mov    w14, #2
    WORD $0xab0c016b // adds    x11, x11, x12
    WORD $0x8b0e01ad // add    x13, x13, x14
    BLE LBB0_21
LBB0_135:
    WORD $0x394001ac // ldrb    w12, [x13]
    WORD $0x7101719f // cmp    w12, #92
    BEQ LBB0_134
    WORD $0x7100899f // cmp    w12, #34
    BEQ LBB0_138
    WORD $0x9280000c // mov    x12, #-1
    WORD $0x5280002e // mov    w14, #1
    WORD $0xab0c016b // adds    x11, x11, x12
    WORD $0x8b0e01ad // add    x13, x13, x14
    BGT LBB0_135
    B LBB0_21
LBB0_138:
    WORD $0xcb0a01aa // sub    x10, x13, x10
    WORD $0x9100054a // add    x10, x10, #1
    WORD $0xf900002a // str    x10, [x1]
    WORD $0xaa0803e0 // mov    x0, x8
    WORD $0x910043ff // add sp, sp, #16
    WORD $0x043f503f // addvl   sp, sp, #1
    WORD $0xa945fbfd // ldp    fp, lr, [sp, #88]
    WORD $0x9101c3ff // add    sp, sp, #112
    WORD $0xd65f03c0 // ret
MASK_USE_NUMBER:
    WORD $0x00000002 // .long    2


TEXT ·__skip_one_fast(SB), NOSPLIT, $0-24
	NO_LOCAL_POINTERS

_entry:
	MOVD 16(g), R16
	SUB $256, RSP, R17
	CMP  R16, R17
	BLS  _stack_grow

_skip_one_fast:
	MOVD s+0(FP), R0
	MOVD p+8(FP), R1
	MOVD ·_subr__skip_one_fast(SB), R11
	WORD $0x1000005e // adr x30, .+8
	JMP (R11)
	MOVD R0, ret+16(FP)
	RET

_stack_grow:
	MOVD R30, R3
	CALL runtime·morestack_noctxt<>(SB)
	JMP  _entry
