// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sve_wrapgoc

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f32toa = 0
)

const (
    _stack__f32toa = 0
)

const (
    _size__f32toa = 3904
)

var (
    _pcsp__f32toa = [][2]uint32{
        {0x1, 0},
        {0xf40, 0},
    }
)

var _cfunc_f32toa = []loader.CFunc{
    {"_f32toa_entry", 0,  _entry__f32toa, 0, nil},
    {"_f32toa", _entry__f32toa, _size__f32toa, _stack__f32toa, _pcsp__f32toa},
}
