// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sve_wrapgoc

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__get_by_path = 0
)

const (
    _stack__get_by_path = 304
)

const (
    _size__get_by_path = 19396
)

var (
    _pcsp__get_by_path = [][2]uint32{
        {0x1, 0},
        {0x2c, 256},
        {0x30, 288},
        {0x3f4c, 304},
        {0x3f50, 288},
        {0x3f7c, 256},
        {0x3f80, 0},
        {0x4bc4, 304},
    }
)

var _cfunc_get_by_path = []loader.CFunc{
    {"_get_by_path_entry", 0,  _entry__get_by_path, 0, nil},
    {"_get_by_path", _entry__get_by_path, _size__get_by_path, _stack__get_by_path, _pcsp__get_by_path},
}
