// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sve_wrapgoc

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__parse_with_padding = 184
)

const (
    _stack__parse_with_padding = 192
)

const (
    _size__parse_with_padding = 57716
)

var (
    _pcsp__parse_with_padding = [][2]uint32{
        {0x1, 0},
        {0x20, 144},
        {0x24, 176},
        {0x158c, 192},
        {0x1590, 176},
        {0x15c4, 144},
        {0x15c8, 0},
        {0xe174, 192},
    }
)

var _cfunc_parse_with_padding = []loader.CFunc{
    {"_parse_with_padding_entry", 0,  _entry__parse_with_padding, 0, nil},
    {"_parse_with_padding", _entry__parse_with_padding, _size__parse_with_padding, _stack__parse_with_padding, _pcsp__parse_with_padding},
}
