// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sve_wrapgoc

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_one = 0
)

const (
    _stack__skip_one = 256
)

const (
    _size__skip_one = 14644
)

var (
    _pcsp__skip_one = [][2]uint32{
        {0x1, 0},
        {0x20, 208},
        {0x24, 240},
        {0x33ec, 256},
        {0x33f0, 240},
        {0x3410, 208},
        {0x3414, 0},
        {0x3934, 256},
    }
)

var _cfunc_skip_one = []loader.CFunc{
    {"_skip_one_entry", 0,  _entry__skip_one, 0, nil},
    {"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
}
