// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sve_wrapgoc

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_one_fast = 0
)

const (
    _stack__skip_one_fast = 160
)

const (
    _size__skip_one_fast = 3492
)

var (
    _pcsp__skip_one_fast = [][2]uint32{
        {0x1, 0},
        {0xc, 112},
        {0x10, 144},
        {0x114, 160},
        {0x118, 144},
        {0x120, 112},
        {0x124, 0},
        {0x29c, 160},
        {0x2a0, 144},
        {0x2a8, 112},
        {0x2ac, 0},
        {0x318, 160},
        {0x31c, 144},
        {0x324, 112},
        {0x328, 0},
        {0x6e4, 160},
        {0x6e8, 144},
        {0x6f0, 112},
        {0x6f4, 0},
        {0xb48, 160},
        {0xb4c, 144},
        {0xb54, 112},
        {0xb58, 0},
        {0xb64, 160},
        {0xb68, 144},
        {0xb70, 112},
        {0xb74, 0},
        {0xb94, 160},
        {0xb98, 144},
        {0xba0, 112},
        {0xba4, 0},
        {0xc34, 160},
        {0xc38, 144},
        {0xc40, 112},
        {0xc44, 0},
        {0xc54, 160},
        {0xc58, 144},
        {0xc60, 112},
        {0xc64, 0},
        {0xce8, 160},
        {0xcec, 144},
        {0xcf4, 112},
        {0xcf8, 0},
        {0xdac, 160},
    }
)

var _cfunc_skip_one_fast = []loader.CFunc{
    {"_skip_one_fast_entry", 0,  _entry__skip_one_fast, 0, nil},
    {"_skip_one_fast", _entry__skip_one_fast, _size__skip_one_fast, _stack__skip_one_fast, _pcsp__skip_one_fast},
}
